version: '2.1'
services:
  site:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: "develop/node/kakou_liwen"
    image: "lopydev/node10"
    container_name: "dev_express_starter"
    ports:
      - "0.0.0.0:50006:3000"
    volumes:
      - app:/app
    env_file:
      - .env
    networks:
      - frontend
    user: node
    working_dir: /app
    command: ["yarn","run","dev"]
volumes:
  app:
    driver: local
    driver_opts:
      type: none
      device: $PWD
      o: bind
networks:
  frontend:
    external:
      name: frontend