version: '2.1'
services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    image: "develop/node/express_starter"
    container_name: "dev_express_starter"
    ports:
      - "0.0.0.0:50000:3000"
    volumes:
      - app:/app
    env_file:
      - .env
    networks:
      - frontend
volumes:
  app:
    driver: local
    driver_opts:
      type: none
      device: $PWD
      o: bind
networks:
  frontend:
    external:
      name: frontend